spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      platform: h2


  h2:
    console:
      enabled: true

app:
  security:
    jwt:
      secret-key: ${JWT_TOKEN}
    auth:
      white-list:
        - "/error"
        - "/auth/**"
        - "/h2-console/**"
        - "/ws/**"

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web.socket: DEBUG
